config/routes.rb
Rails.application.routes.draw do
  resources :productions
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/models/api_key.rb
class ApiKey < ApplicationRecord

before_create :generate_access_token


private 

	def generate_access_token
		begin
			self.access_token = SecureRandom.hex
		end while self.class.exists?(access_token: access_token)
	end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/production.rb
class Production < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController



def index

end


end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  before_action :set_production, only: [:show, :edit, :update, :destroy]


  @token = ""
   #http_basic_authenticate_with name: "admin", password: "secret"
   before_filter :restrict_access
  # GET /productions
  # GET /productions.json
  def index
    
    
    @a = ApiKey.find_by_access_token(@token)


    render json: {:status => "OK", :user_id => "#{@a.user_id}"}
  end

  # GET /productions/1
  # GET /productions/1.json
  def show
  end

  # GET /productions/new
  def new
    @production = Production.new
  end

  # GET /productions/1/edit
  def edit
  end

  # POST /productions
  # POST /productions.json
  def create
    @production = Production.new(production_params)

    respond_to do |format|
      if @production.save
        format.html { redirect_to @production, notice: 'Production was successfully created.' }
        format.json { render :show, status: :created, location: @production }
      else
        format.html { render :new }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productions/1
  # PATCH/PUT /productions/1.json
  def update
    respond_to do |format|
      if @production.update(production_params)
        format.html { redirect_to @production, notice: 'Production was successfully updated.' }
        format.json { render :show, status: :ok, location: @production }
      else
        format.html { render :edit }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productions/1
  # DELETE /productions/1.json
  def destroy
    @production.destroy
    respond_to do |format|
      format.html { redirect_to productions_url, notice: 'Production was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_production
      @production = Production.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def production_params
      params.require(:production).permit(:name, :price)
    end


private

  def restrict_access
    authenticate_or_request_with_http_token do |token, options|
      if ApiKey.exists?(access_token: token)
        @token = token
      else
        render json: {:message => "error"}
      end
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productions_helper.rb
module ProductionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%if admin_signed_in?%>

  		zalogowano
  		<li><%=link_to "log out", destroy_admin_session_url, :method=> 'delete' %></li>
  	<%else%>
  		<li><%=link_to "log in", new_admin_session_url%></li>
  		niezalogowano	
  	<%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>index</h1>

app/views/productions/_form.html.erb
<%= form_for(production) do |f| %>
  <% if production.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(production.errors.count, "error") %> prohibited this production from being saved:</h2>

      <ul>
      <% production.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productions/edit.html.erb
<h1>Editing Production</h1>

<%= render 'form', production: @production %>

<%= link_to 'Show', @production %> |
<%= link_to 'Back', productions_path %>

app/views/productions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productions.each do |production| %>
      <tr>
        <td><%= production.name %></td>
        <td><%= production.price %></td>
        <td><%= link_to 'Show', production %></td>
        <td><%= link_to 'Edit', edit_production_path(production) %></td>
        <td><%= link_to 'Destroy', production, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Production', new_production_path %>

app/views/productions/new.html.erb
<h1>New Production</h1>

<%= render 'form', production: @production %>

<%= link_to 'Back', productions_path %>

app/views/productions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @production.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @production.price %>
</p>

<%= link_to 'Edit', edit_production_path(@production) %> |
<%= link_to 'Back', productions_path %>